from mongo:3.4
RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get install python3 -y
ADD ecryptfs_setup.sh /ecryptfs_setup.sh 
RUN ./ecryptfs_setup.sh
ADD mongo_start_script.sh /start_script.sh
ADD mount_ecryptfs.sh /mount_ecryptfs.sh
ADD encrypt.py /encrypt.py
CMD ["./start_script.sh"] 
